name: funing
title: funing
base: core18
version: git
summary: funing
description: |
  a face recognition GUI
icon: src/logo.svg
license: MIT
apps: 
  funing:
    command: usr/sbin

confinement: classic

parts:
  funing:
    plugin: python
    python-version: python3
    source: ./funing/
    source-type: git
    stage-packages:
      - dlib
      - face-recognition
      - language_data
      - langcodes
      - pony
      - opencv-python
      - pyyaml

