set tabstop=4
set title
set laststatus=2
set hlsearch
set shiftwidth=4
set incsearch
set wildmenu
set wildmode=list:longest
set softtabstop=4
set expandtab
set number
set showcmd
set showmatch
set colorcolumn=80
set ruler
set wrap
set linebreak
set statusline+=%F
set statusline+=%=
set statusline+=%p%%
set statusline+=(%l:%c)
set textwidth=79
set formatoptions+=w
set fenc=utf-8 
set autoindent
set smartindent
set smarttab
set expandtab

